CREATE TABLE atributo
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome         VARCHAR(255),
    valor_atual  INTEGER                                 NOT NULL,
    valor_minimo INTEGER                                 NOT NULL,
    valor_maximo INTEGER                                 NOT NULL,
    sistema      VARCHAR(255),
    ficha_id     BIGINT,
    CONSTRAINT pk_atributo PRIMARY KEY (id)
);

CREATE TABLE campanha
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    master      VARCHAR(255),
    qtd_players INTEGER                                 NOT NULL,
    sistema_id  BIGINT                                  NOT NULL,
    user_id     BIGINT,
    CONSTRAINT pk_campanha PRIMARY KEY (id)
);

CREATE TABLE ficha
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome        VARCHAR(255),
    raca        VARCHAR(255),
    classe      VARCHAR(255),
    nivel       INTEGER                                 NOT NULL,
    vida        INTEGER                                 NOT NULL,
    mana        INTEGER                                 NOT NULL,
    campanha_id BIGINT,
    CONSTRAINT pk_ficha PRIMARY KEY (id)
);

CREATE TABLE ficha_habilidades
(
    ficha_id      BIGINT NOT NULL,
    habilidade_id BIGINT NOT NULL
);

CREATE TABLE ficha_inventario
(
    ficha_id BIGINT NOT NULL,
    item_id  BIGINT NOT NULL
);

CREATE TABLE habilidade
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome      VARCHAR(255),
    descricao VARCHAR(255),
    custo     INTEGER                                 NOT NULL,
    sistema   VARCHAR(255),
    CONSTRAINT pk_habilidade PRIMARY KEY (id)
);

CREATE TABLE herouser
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255),
    email      VARCHAR(255),
    avatar_url VARCHAR(255),
    CONSTRAINT pk_herouser PRIMARY KEY (id)
);

CREATE TABLE item
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome      VARCHAR(255),
    descricao VARCHAR(255),
    poder     INTEGER                                 NOT NULL,
    sistema   VARCHAR(255),
    CONSTRAINT pk_item PRIMARY KEY (id)
);

CREATE TABLE sistema
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome     VARCHAR(255),
    vida_min INTEGER                                 NOT NULL,
    vida_max INTEGER                                 NOT NULL,
    mana_min INTEGER                                 NOT NULL,
    mana_max INTEGER                                 NOT NULL,
    CONSTRAINT pk_sistema PRIMARY KEY (id)
);

CREATE TABLE sistema_classes
(
    sistema_id BIGINT NOT NULL,
    classes    VARCHAR(255)
);

CREATE TABLE sistema_racas
(
    sistema_id BIGINT NOT NULL,
    racas      VARCHAR(255)
);

ALTER TABLE herouser
    ADD CONSTRAINT uc_herouser_email UNIQUE (email);

ALTER TABLE atributo
    ADD CONSTRAINT FK_ATRIBUTO_ON_FICHA FOREIGN KEY (ficha_id) REFERENCES ficha (id);

ALTER TABLE campanha
    ADD CONSTRAINT FK_CAMPANHA_ON_SISTEMA FOREIGN KEY (sistema_id) REFERENCES sistema (id);

ALTER TABLE campanha
    ADD CONSTRAINT FK_CAMPANHA_ON_USER FOREIGN KEY (user_id) REFERENCES herouser (id);

ALTER TABLE ficha
    ADD CONSTRAINT FK_FICHA_ON_CAMPANHA FOREIGN KEY (campanha_id) REFERENCES campanha (id);

ALTER TABLE ficha_habilidades
    ADD CONSTRAINT fk_fichab_on_ficha FOREIGN KEY (ficha_id) REFERENCES ficha (id);

ALTER TABLE ficha_habilidades
    ADD CONSTRAINT fk_fichab_on_habilidade FOREIGN KEY (habilidade_id) REFERENCES habilidade (id);

ALTER TABLE ficha_inventario
    ADD CONSTRAINT fk_ficinv_on_ficha FOREIGN KEY (ficha_id) REFERENCES ficha (id);

ALTER TABLE ficha_inventario
    ADD CONSTRAINT fk_ficinv_on_item FOREIGN KEY (item_id) REFERENCES item (id);

ALTER TABLE sistema_classes
    ADD CONSTRAINT fk_sistema_classes_on_sistema FOREIGN KEY (sistema_id) REFERENCES sistema (id);

ALTER TABLE sistema_racas
    ADD CONSTRAINT fk_sistema_racas_on_sistema FOREIGN KEY (sistema_id) REFERENCES sistema (id);