CREATE TABLE atributo
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome         VARCHAR(255),
    valor_atual  INTEGER                                 NOT NULL,
    valor_minimo INTEGER                                 NOT NULL,
    valor_maximo INTEGER                                 NOT NULL,
    sistema      VARCHAR(255),
    CONSTRAINT pk_atributo PRIMARY KEY (id)
);

CREATE TABLE campanha
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    master      VARCHAR(255),
    qtd_players INTEGER                                 NOT NULL,
    sistema_id  BIGINT,
    CONSTRAINT pk_campanha PRIMARY KEY (id)
);

CREATE TABLE ficha
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome        VARCHAR(255),
    raca        VARCHAR(255),
    classe      VARCHAR(255),
    nivel       INTEGER                                 NOT NULL,
    vida        INTEGER                                 NOT NULL,
    mana        INTEGER                                 NOT NULL,
    campanha_id BIGINT,
    CONSTRAINT pk_ficha PRIMARY KEY (id)
);

CREATE TABLE ficha_atributos
(
    ficha_id     BIGINT NOT NULL,
    atributos_id BIGINT NOT NULL
);

CREATE TABLE ficha_habilidades
(
    ficha_id       BIGINT NOT NULL,
    habilidades_id BIGINT NOT NULL
);

CREATE TABLE ficha_inventario
(
    ficha_id      BIGINT NOT NULL,
    inventario_id BIGINT NOT NULL
);

CREATE TABLE habilidade
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome      VARCHAR(255),
    descricao VARCHAR(255),
    custo     INTEGER                                 NOT NULL,
    sistema   VARCHAR(255),
    CONSTRAINT pk_habilidade PRIMARY KEY (id)
);

CREATE TABLE item
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome      VARCHAR(255),
    descricao VARCHAR(255),
    poder     INTEGER                                 NOT NULL,
    sistema   VARCHAR(255),
    CONSTRAINT pk_item PRIMARY KEY (id)
);

CREATE TABLE sistema
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome     VARCHAR(255),
    vida_min INTEGER                                 NOT NULL,
    vida_max INTEGER                                 NOT NULL,
    mana_min INTEGER                                 NOT NULL,
    mana_max INTEGER                                 NOT NULL,
    CONSTRAINT pk_sistema PRIMARY KEY (id)
);

CREATE TABLE sistema_classes
(
    sistema_id BIGINT NOT NULL,
    classes    VARCHAR(255)
);

CREATE TABLE sistema_racas
(
    sistema_id BIGINT NOT NULL,
    racas      VARCHAR(255)
);

ALTER TABLE ficha_atributos
    ADD CONSTRAINT uc_ficha_atributos_atributos UNIQUE (atributos_id);

ALTER TABLE ficha_habilidades
    ADD CONSTRAINT uc_ficha_habilidades_habilidades UNIQUE (habilidades_id);

ALTER TABLE ficha_inventario
    ADD CONSTRAINT uc_ficha_inventario_inventario UNIQUE (inventario_id);

ALTER TABLE campanha
    ADD CONSTRAINT FK_CAMPANHA_ON_SISTEMA FOREIGN KEY (sistema_id) REFERENCES sistema (id);

ALTER TABLE ficha
    ADD CONSTRAINT FK_FICHA_ON_CAMPANHA FOREIGN KEY (campanha_id) REFERENCES campanha (id);

ALTER TABLE ficha_atributos
    ADD CONSTRAINT fk_ficatr_on_atributo FOREIGN KEY (atributos_id) REFERENCES atributo (id);

ALTER TABLE ficha_atributos
    ADD CONSTRAINT fk_ficatr_on_ficha FOREIGN KEY (ficha_id) REFERENCES ficha (id);

ALTER TABLE ficha_habilidades
    ADD CONSTRAINT fk_fichab_on_ficha FOREIGN KEY (ficha_id) REFERENCES ficha (id);

ALTER TABLE ficha_habilidades
    ADD CONSTRAINT fk_fichab_on_habilidade FOREIGN KEY (habilidades_id) REFERENCES habilidade (id);

ALTER TABLE ficha_inventario
    ADD CONSTRAINT fk_ficinv_on_ficha FOREIGN KEY (ficha_id) REFERENCES ficha (id);

ALTER TABLE ficha_inventario
    ADD CONSTRAINT fk_ficinv_on_item FOREIGN KEY (inventario_id) REFERENCES item (id);

ALTER TABLE sistema_classes
    ADD CONSTRAINT fk_sistema_classes_on_sistema FOREIGN KEY (sistema_id) REFERENCES sistema (id);

ALTER TABLE sistema_racas
    ADD CONSTRAINT fk_sistema_racas_on_sistema FOREIGN KEY (sistema_id) REFERENCES sistema (id);